ARG RUNTIME
ARG VERSION
ARG ARCH
FROM mlupin/lambda-base-2023:build-${ARCH} as build

FROM public.ecr.aws/lambda/${RUNTIME}:${VERSION}

ENV PATH=/var/lang/bin:$PATH \
    LD_LIBRARY_PATH=/lib64:/usr/lib64:/var/lang/lib:$LD_LIBRARY_PATH \
    AWS_EXECUTION_ENV=AWS_Lambda_nodejs"${VERSION}".x \
    AWS_EXECUTION_ARCH="${ARCH}" \
    NODE_PATH=/opt/nodejs/node"${VERSION}"/node_modules:/opt/nodejs/node_modules:/var/runtime/node_modules

COPY --from=build /var/runtime/init /var/rapid/init

ENTRYPOINT ["/var/rapid/init", "--bootstrap", "/var/runtime/bootstrap", "--enable-msg-logs"]
