ARG RUNTIME
ARG VERSION
ARG ARCH
FROM mlupin/lambda-base-2023:build-${ARCH} as build

FROM public.ecr.aws/lambda/${RUNTIME}:${VERSION}

ENV PATH=/var/lang/bin:$PATH \
    LD_LIBRARY_PATH=/lib64:/usr/lib64:/var/lang/lib:$LD_LIBRARY_PATH \
    AWS_EXECUTION_ENV=AWS_Lambda_${RUNTIME}${VERSION} \
    AWS_EXECUTION_ARCH="${ARCH}" \
    PKG_CONFIG_PATH=/var/lang/lib/pkgconfig:/usr/lib64/pkgconfig:/usr/share/pkgconfig

COPY --from=build /var/runtime/init /var/rapid/init

ENTRYPOINT ["/var/rapid/init", "--bootstrap", "/var/runtime/bootstrap", "--enable-msg-logs"]
