ARG RUNTIME
ARG VERSION
FROM public.ecr.aws/lambda/${RUNTIME}:${VERSION} as amazonlinux

FROM mlupin/lambda-base-2023:build

ARG ARCH
ARG VERSION

ENV PATH=/var/lang/bin:$PATH \
    LD_LIBRARY_PATH=/lib64:/usr/lib64:/var/lang/lib:$LD_LIBRARY_PATH \
    AWS_EXECUTION_ENV=AWS_Lambda_ruby3.2 \
    AWS_EXECUTION_ARCH=x86_64 \
    GEM_HOME=/var/runtime \
    GEM_PATH=/var/task/vendor/bundle/ruby/3.2.0:/opt/ruby/gems/3.2.0:/var/lang/lib/ruby/gems/3.2.0 \
    RUBYLIB=/var/task:/var/runtime/lib:/opt/ruby/lib \
    BUNDLE_SILENCE_ROOT_WARNING=1

COPY --from=amazonlinux /var/runtime /var/runtime
COPY --from=amazonlinux /var/lang /var/lang
COPY --from=amazonlinux /var/rapid /var/rapid

# Add these as a separate layer as they get updated frequently
RUN pipx install awscli && \
  pipx install aws-lambda-builders && \
  pipx install aws-sam-cli && \
  gem update --system --no-document && \
  gem install --no-document bundler -v '~> 2.1'